#!/bin/sh
#
# SPDX-License-Identifier: Apache-2.0
#
# This file was generated by Gradle.
# Distribution Url: https\://services.gradle.org/distributions/gradle-8.7-bin.zip
#
set -e

APP_BASE_NAME=${0##*/}
APP_HOME=$(cd "${0%/*}" && pwd)

JAVA_HOME="${JAVA_HOME:-}"
if [ -n "$JAVA_HOME" ]; then
  JAVA_BIN="$JAVA_HOME/bin/java"
else
  JAVA_BIN="java"
fi

# Collect all arguments for the java command
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine OS
cygwin=false
msys=false
case "$(uname)" in
  CYGWIN* ) cygwin=true ;;
  MINGW* ) msys=true ;;
esac

# For Cygwin/MSYS, switch paths to Windows format before running java
if $cygwin || $msys ; then
  APP_HOME=$(cygpath --path --mixed "$APP_HOME")
  CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
fi

exec "$JAVA_BIN" -Xmx64m -Xms64m -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
